db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "![CVn9wxhqr5A=]"
  database: "usecase"
  
http:
  port: "8085"
  protocol: "HTTP"
  
ftp:
  host: "localhost"
  port: "21"
  username: "usecase"
  password: "![CVn9wxhqr5A=]"